const usernames = [
  "coolCoder123",
  "blueberryPie",
  "codeNinja42",
  "jazzPianoPlayer",
  "mountainExplorer",
  "techGuru99",
  "pineapplePizzaLover",
  "midnightDreamer",
  "sunnyDayz",
  "gamingMastermind",
  "coffeeAddict22",
  "moonlightSerenade",
  "adventureSeeker88",
  "secretAgentX",
  "bananaSplit",
  "codeWizard2022",
  "guitarHero123",
  "starGazer77",
  "snowboardPro",
  "codingWarrior",
  "bookworm82",
  "beachBum55",
  "pizzaFanatic",
  "skydiverExtreme",
  "codeJunkie007",
  "movieBuff99",
  "danceFloorKing",
  "theGreatGatsby",
  "coffeeShopRegular",
  "gamingChampion",
  "musicMaestro88",
  "codeCrusader42",
  "wildernessExplorer",
  "techEnthusiast22",
  "sunsetChaser",
  "snowballFighter",
  "codeSlinger",
  "soccerFanatic99",
  "jungleExplorer",
  "codingNinja42",
  "teaLover77",
  "moonwalker2022",
];

const users = [
  { "username": "coolCoder123", "email": "coolCoder123@example.com" },
  { "username": "blueberryPie", "email": "blueberryPie@example.com" },
  { "username": "codeNinja42", "email": "codeNinja42@example.com" },
  { "username": "jazzPianoPlayer", "email": "jazzPianoPlayer@example.com" },
  { "username": "mountainExplorer", "email": "mountainExplorer@example.com" },
  { "username": "techGuru99", "email": "techGuru99@example.com" },
  { "username": "pineapplePizzaLover", "email": "pineapplePizzaLover@example.com" },
  { "username": "midnightDreamer", "email": "midnightDreamer@example.com" },
  { "username": "sunnyDayz", "email": "sunnyDayz@example.com" },
  { "username": "gamingMastermind", "email": "gamingMastermind@example.com" },
  { "username": "coffeeAddict22", "email": "coffeeAddict22@example.com" },
  { "username": "moonlightSerenade", "email": "moonlightSerenade@example.com" },
  { "username": "adventureSeeker88", "email": "adventureSeeker88@example.com" },
  { "username": "secretAgentX", "email": "secretAgentX@example.com" },
  { "username": "bananaSplit", "email": "bananaSplit@example.com" },
  { "username": "codeWizard2022", "email": "codeWizard2022@example.com" },
  { "username": "guitarHero123", "email": "guitarHero123@example.com" },
  { "username": "starGazer77", "email": "starGazer77@example.com" },
  { "username": "snowboardPro", "email": "snowboardPro@example.com" },
  { "username": "codingWarrior", "email": "codingWarrior@example.com" },
  { "username": "bookworm82", "email": "bookworm82@example.com" },
  { "username": "beachBum55", "email": "beachBum55@example.com" },
  { "username": "pizzaFanatic", "email": "pizzaFanatic@example.com" },
  { "username": "skydiverExtreme", "email": "skydiverExtreme@example.com" },
  { "username": "codeJunkie007", "email": "codeJunkie007@example.com" },
  { "username": "movieBuff99", "email": "movieBuff99@example.com" },
  { "username": "danceFloorKing", "email": "danceFloorKing@example.com" },
  { "username": "theGreatGatsby", "email": "theGreatGatsby@example.com" },
  { "username": "coffeeShopRegular", "email": "coffeeShopRegular@example.com" },
  { "username": "gamingChampion", "email": "gamingChampion@example.com" },
  { "username": "musicMaestro88", "email": "musicMaestro88@example.com" },
  { "username": "codeCrusader42", "email": "codeCrusader42@example.com" },
  { "username": "wildernessExplorer", "email": "wildernessExplorer@example.com" },
  { "username": "techEnthusiast22", "email": "techEnthusiast22@example.com" },
  { "username": "sunsetChaser", "email": "sunsetChaser@example.com" },
  { "username": "snowballFighter", "email": "snowballFighter@example.com" },
  { "username": "codeSlinger", "email": "codeSlinger@example.com" },
  { "username": "soccerFanatic99", "email": "soccerFanatic99@example.com" },
  { "username": "jungleExplorer", "email": "jungleExplorer@example.com" },
  { "username": "codingNinja42", "email": "codingNinja42@example.com" },
  { "username": "teaLover77", "email": "teaLover77@example.com" },
  { "username": "moonwalker2022", "email": "moonwalker2022@example.com" },
];

const thoughts = [
  "JavaScript: My Favorite Language and Why You Should Learn It",
  "The Beauty of JavaScript: Why It's My Top Programming Language",
  "JavaScript Mastery: How I Fell in Love with Coding",
  "Why JavaScript Is My Go-To Language for Web Development",
  "JavaScript Delight: Exploring the Wonders of Coding",
  "JavaScript Awesomeness: A Journey into Programming Bliss",
  "JavaScript Love: My Passion for Coding",
  "The Joy of JavaScript: My Favorite Language Revealed",
  "JavaScript Magic: Unlocking the Secrets of Coding",
  "JavaScript Wonder: The Language That Changed My Life",
  "JavaScript Dreams: Why It's My Favorite Language",
  "The Art of JavaScript: Mastering the Language of the Web",
  "JavaScript Adventure: My Journey into Programming Excellence",
  "JavaScript Enchantment: The Spellbinding World of Coding",
  "JavaScript Inspiration: How It Became My Favorite Language",
  "JavaScript Euphoria: Why Coding in JS is Pure Joy",
  "The Power of JavaScript: My Love for Programming",
  "JavaScript Excitement: Discovering the Thrill of Coding",
  "JavaScript Bliss: How It Became My Favorite Language",
  "JavaScript Joyride: My Adventures in Programming",
  "JavaScript Rhapsody: A Love Letter to Coding",
  "JavaScript Reverie: Dreaming in Code",
  "JavaScript Ecstasy: The Language of Innovation",
  "JavaScript Symphony: Creating Harmonious Code",
  "JavaScript Serenity: Finding Peace in Programming",
  "JavaScript Inspiration: Fueling Creativity in Code",
  "JavaScript Odyssey: A Journey into Web Development",
  "JavaScript Nirvana: Reaching Programming Paradise",
  "JavaScript Harmony: The Perfect Language for Web Development",
  "JavaScript Discovery: Unveiling the Secrets of Coding",
  "JavaScript Revelation: How It Became My Favorite Language",
  "JavaScript Evolution: The Language That Grows with You",
  "JavaScript Discovery: Exploring the Depths of Coding",
  "JavaScript Infinity: The Endless Possibilities of Coding",
  "JavaScript Illumination: Shedding Light on the World of Programming",
  "JavaScript Revolution: Changing the Game in Web Development",
  "JavaScript Innovation: Pioneering New Horizons in Coding",
  "JavaScript Fusion: Blending Creativity and Logic in Code",
  "JavaScript Zen: Finding Balance in Programming",
  "JavaScript Legacy: Building a Lasting Impact with Code",
  "JavaScript Vision: Seeing the Future of Web Development",
  "JavaScript Imagination: Creating Magic with Code",
];

const reactions = [
  "I agree.",
  "I'm not sure I understand why, does anyone else feel that?",
  "This is so helpful, thanks!",
  "Great explanation!",
  "I never thought of it that way, thanks for sharing!",
  "Can you clarify this point a bit more?",
  "I'm loving this discussion!",
  "Wow, mind blown!",
  "I'm a bit confused, can someone explain this differently?",
  "I totally disagree with this",
  "This is exactly what I needed, thank you!",
  "I'm not sure about this approach, anyone have other suggestions?",
  "This has really helped me understand better",
  "I'm struggling with this concept, any tips?",
  "I'm on the fence about this",
  "I've had a similar experience, thanks for sharing!",
  "I've never thought of it like that before",
  "I'm so grateful for this explanation",
  "I'm so lost, can someone help me?",
  "I'm not sure I agree with this",
  "I'm blown away by this explanation",
  "I'm struggling to see the relevance here",
  "I'm so excited to try this out!",
  "I'm not sure this is correct, can someone confirm?",
  "I'm finding this really challenging, any advice?",
  "I'm loving the insights in this discussion",
  "I'm curious to hear other perspectives on this",
  "I'm so inspired by this",
  "I'm feeling a bit overwhelmed, can someone simplify this?",
  "I'm not sure where to start with this",
  "I'm finding this really confusing, can someone help me understand?",
  "I'm not sure this is the best approach",
  "I'm not sure I agree with this interpretation",
  "I'm so grateful for the detail in this explanation",
  "I'm finding this really interesting",
  "I'm not sure this is relevant to me",
  "I'm struggling to see how this applies to my situation",
  "I'm so impressed by the depth of this discussion",
  "I'm not sure I follow, can you explain this differently?",
  "I'm not sure I see the value in this",
  "I'm so grateful for the effort that went into this explanation",
  "I'm finding this really insightful",
  "I'm not sure I understand the context here",
  "I'm not sure this is the right approach for me",
  "I'm so excited to learn more about this",
  "I'm feeling a bit lost, can someone point me in the right direction?",
  "I'm not sure I agree with this assessment",
  "I'm so impressed by the knowledge in this discussion",
  "I'm struggling to see the connection here",
  "I'm not sure this is the best solution",
  "I'm not sure this is relevant to my work",
  "I'm so grateful for the clarity in this explanation",
  "I'm finding this really helpful",
  "I'm not sure this is the right path for me",
  "I'm not sure I see the point of this",
  "I'm so inspired by the ideas in this discussion",
  "I'm not sure I understand the purpose here",
  "I'm not sure this is the best way to approach this",
  "I'm so excited to implement this",
  "I'm feeling a bit overwhelmed, can someone break this down for me?",
  "I'm not sure I agree with this conclusion",
  "I'm so impressed by the expertise in this discussion",
  "I'm struggling to see how this applies to my project",
  "I'm not sure I follow, can you provide more detail?",
  "I'm not sure I see the benefit of this",
  "I'm so grateful for the insights in this explanation",
  "I'm finding this really enlightening",
  "I'm not sure I understand the relevance here",
  "I'm not sure this is the right fit for me",
  "I'm so excited to dive deeper into this",
  "I'm feeling a bit lost, can someone give me some guidance?",
  "I'm not sure I agree with this perspective",
  "I'm so impressed by the analysis in this discussion",
  "I'm struggling to see how this fits into the bigger picture",
  "I'm not sure this is the most efficient way to do this",
  "I'm not sure this is applicable to my situation",
  "I'm so grateful for the depth in this explanation",
  "I'm finding this really thought-provoking",
  "I'm not sure I understand the context here",
  "I'm not sure this is the right approach for my project",
  "I'm so excited to see where this leads",
  "I'm feeling a bit overwhelmed, can someone simplify this for me?",
  "I'm not sure I agree with this interpretation",
  "I'm so impressed by the expertise in this discussion",
  "I'm struggling to see how this applies to my work",
  "I'm not sure I follow, can you provide more context?",
  "I'm not sure I see the value in this",
  "I'm so grateful for the insights in this explanation",
];

const randomThing = (arr) => arr[Math.floor(Math.random() * arr.length)];

const randomUsername = () => randomThing(usernames);

const randomUser = () => randomThing(users);

const randomThought = (int) => {
  let results = [];
  for (let i = 0; i < int; i++) {
    const numReactions = Math.floor(Math.random() * 7 + 1);
    let thought = {
      thoughtText: randomThing(thoughts),
      username: randomUsername(),
      reactions: [],
    };
    for (let j = 0; j < numReactions; j++) {
      thought.reactions.push({
        reactionBody: randomThing(reactions),
        username: randomUsername(),
      });
    }
    results.push(thought);
  }
  return results;
};

const randomFriends = () => {
  const numFriends = Math.floor(Math.random() * 7 + 1);
  let friends = [];
  for (let i = 0; i < numFriends; i++) {
    const friend = randomUser();
    friends.push(friend);
  }
  return friends;
};

module.exports = { randomUser, randomThought, randomFriends };
